# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [23]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [24]:

weather_data_df=pd.read_csv("../output_data/cities.csv")

weather_data_df

,Unnamed: 0,City,Latitude,Longtitude,Temp,Cloudiness,Wind Speed,Humidity
0,0,kapaa,22.0752,-159.3190,17.12,75,2.57,77
1,1,bela,25.9333,81.9833,15.62,76,1.45,72
2,2,chokurdakh,70.6333,147.9167,-25.01,98,6.21,88
3,3,richards bay,-28.7830,32.0377,23.96,30,0.90,93
4,4,san antonio,29.4241,-98.4936,11.38,90,5.66,40
...,...,...,...,...,...,...,...,...
555,555,sakete,6.7362,2.6587,31.00,20,5.66,74
556,556,margate,51.3813,1.3862,8.33,0,0.89,82
557,557,panguna,-6.3164,155.4848,20.88,62,0.97,100
558,558,jiazi,22.8779,116.0670,15.78,0,1.51,80
559,559,bemidji,47.4736,-94.8803,-17.12,1,9.26,71

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [25]:
locations=weather_data_df[["Latitude","Longtitude"]]

humidity_rate=weather_data_df["Humidity"]


fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_rate, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 3)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [26]:
hotel_df=weather_data_df.loc[(weather_data_df["Temp"]>18)&(weather_data_df["Humidity"]<50)]

hotel_df

,Unnamed: 0,City,Latitude,Longtitude,Temp,Cloudiness,Wind Speed,Humidity
5,5,cabo san lucas,22.8909,-109.9124,25.58,1,2.57,41
79,79,tessalit,20.1986,1.0114,26.79,2,4.26,13
112,112,luderitz,-26.6481,15.1594,24.62,0,12.43,47
125,125,bara,10.3744,10.7288,28.37,18,4.51,16
135,135,ortigueira,-24.2083,-50.9494,26.30,0,2.96,48
147,147,okakarara,-20.5833,17.4333,26.81,84,1.59,44
169,169,lahijan,37.2061,50.0029,22.00,75,4.12,28
175,175,san cristobal,7.7669,-72.2250,31.00,40,7.20,48
179,179,veraval,20.9000,70.3667,21.44,0,7.58,34
213,213,yulara,-25.2406,130.9889,21.00,25,3.60,30
235,235,sidi ali,36.0998,0.4206,20.61,83,7.18,29
267,267,padre paraiso,-17.0742,-41.4844,31.20,99,0.76,45
281,281,ondjiva,-17.0667,15.7333,34.00,40,3.09,26
306,306,riyadh,24.6877,46.7219,23.00,0,4.63,14
315,315,coracao de jesus,-16.6853,-44.3650,33.00,40,3.09,35
319,319,lalpur,22.2000,69.9667,19.00,0,4.12,45
339,339,neuquen,-38.9516,-68.0591,36.00,0,3.09,11
374,374,ciudad bolivar,8.1222,-63.5497,33.39,90,5.00,39
379,379,rehoboth,-23.3167,17.0833,28.79,84,6.44,37
388,388,adrar,20.5022,-10.0711,24.39,33,3.50,20
394,394,diu,20.7141,70.9822,18.70,0,2.89,41
429,429,moussoro,13.6408,16.4901,24.08,0,5.61,18
433,433,paraiso,9.8383,-83.8656,27.53,0,5.66,47
438,438,umm kaddadah,13.6017,26.6876,18.96,0,7.45,25
455,455,guerrero negro,27.9769,-114.0611,18.92,0,3.44,49
459,459,almeirim,-1.5233,-52.5817,33.00,48,2.75,49
460,460,nalut,30.3333,10.8500,18.48,84,5.53,26
463,463,san rafael,-34.6177,-68.3301,30.53,0,4.85,19
479,479,moron,-34.6534,-58.6198,27.75,0,1.79,36
482,482,mizdah,31.4451,12.9801,18.25,64,3.51,26
501,501,bongor,10.2806,15.3722,28.03,15,3.32,15
502,502,la reforma,25.0833,-108.0500,25.05,1,4.11,49
506,506,manzil salim,35.8567,8.4765,19.00,0,3.09,15
516,516,amlame,7.4667,0.9000,31.42,57,1.66,40
521,521,bilma,18.6853,12.9164,20.48,3,3.52,23
530,530,necochea,-38.5473,-58.7368,29.33,0,3.91,23
540,540,azare,11.6765,10.1948,26.33,2,5.30,17
541,541,oum hadjer,13.2954,19.6966,24.91,0,4.77,17
542,542,atar,20.5169,-13.0499,22.71,100,4.57,29
554,554,bitkine,11.9801,18.2138,25.56,0,4.27,17

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [27]:
hotel_df["Hotel Name"]=""


params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longtitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
       
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

/Users/cactus/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/cactus/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

In [28]:
hotel_df

,Unnamed: 0,City,Latitude,Longtitude,Temp,Cloudiness,Wind Speed,Humidity,Hotel Name
5,5,cabo san lucas,22.8909,-109.9124,25.58,1,2.57,41,Waldorf Astoria Los Cabos Pedregal
79,79,tessalit,20.1986,1.0114,26.79,2,4.26,13,
112,112,luderitz,-26.6481,15.1594,24.62,0,12.43,47,LÜDERITZ NEST HOTEL
125,125,bara,10.3744,10.7288,28.37,18,4.51,16,
135,135,ortigueira,-24.2083,-50.9494,26.30,0,2.96,48,Hotel Brasil
147,147,okakarara,-20.5833,17.4333,26.81,84,1.59,44,
169,169,lahijan,37.2061,50.0029,22.00,75,4.12,28,Markazi hotel
175,175,san cristobal,7.7669,-72.2250,31.00,40,7.20,48,Lidotel Hotel Boutique San Cristobal
179,179,veraval,20.9000,70.3667,21.44,0,7.58,34,The Bliss Hotel
213,213,yulara,-25.2406,130.9889,21.00,25,3.60,30,Sails in the Desert
235,235,sidi ali,36.0998,0.4206,20.61,83,7.18,29,
267,267,padre paraiso,-17.0742,-41.4844,31.20,99,0.76,45,HOTEL YOGUEDES
281,281,ondjiva,-17.0667,15.7333,34.00,40,3.09,26,Villa Okapale
306,306,riyadh,24.6877,46.7219,23.00,0,4.63,14,Four Seasons Hotel Riyadh At Kingdom Center
315,315,coracao de jesus,-16.6853,-44.3650,33.00,40,3.09,35,Millenium Hotel
319,319,lalpur,22.2000,69.9667,19.00,0,4.12,45,Jay Chhuchhar
339,339,neuquen,-38.9516,-68.0591,36.00,0,3.09,11,Hilton Garden Inn Neuquen
374,374,ciudad bolivar,8.1222,-63.5497,33.39,90,5.00,39,Hotel Valentina
379,379,rehoboth,-23.3167,17.0833,28.79,84,6.44,37,Bastertroos Guesthouse and Cafe
388,388,adrar,20.5022,-10.0711,24.39,33,3.50,20,
394,394,diu,20.7141,70.9822,18.70,0,2.89,41,Rainbow Resort
429,429,moussoro,13.6408,16.4901,24.08,0,5.61,18,
433,433,paraiso,9.8383,-83.8656,27.53,0,5.66,47,Villas Canaveral
438,438,umm kaddadah,13.6017,26.6876,18.96,0,7.45,25,
455,455,guerrero negro,27.9769,-114.0611,18.92,0,3.44,49,Malarrimo Hotel and Restaurant
459,459,almeirim,-1.5233,-52.5817,33.00,48,2.75,49,Kapejar Hotel
460,460,nalut,30.3333,10.8500,18.48,84,5.53,26,
463,463,san rafael,-34.6177,-68.3301,30.53,0,4.85,19,Tower Inn Hotel & Suites Casino Spa Convention...
479,479,moron,-34.6534,-58.6198,27.75,0,1.79,36,The Palm House Hotel
482,482,mizdah,31.4451,12.9801,18.25,64,3.51,26,فندق مزدة الكبير
501,501,bongor,10.2806,15.3722,28.03,15,3.32,15,
502,502,la reforma,25.0833,-108.0500,25.05,1,4.11,49,Hotel Fermin
506,506,manzil salim,35.8567,8.4765,19.00,0,3.09,15,
516,516,amlame,7.4667,0.9000,31.42,57,1.66,40,
521,521,bilma,18.6853,12.9164,20.48,3,3.52,23,
530,530,necochea,-38.5473,-58.7368,29.33,0,3.91,23,Hotel Ñikén Spa & Business Center
540,540,azare,11.6765,10.1948,26.33,2,5.30,17,Hotel
541,541,oum hadjer,13.2954,19.6966,24.91,0,4.77,17,
542,542,atar,20.5169,-13.0499,22.71,100,4.57,29,Odar kanawal
554,554,bitkine,11.9801,18.2138,25.56,0,4.27,17,

In [31]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>

</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longtitude"]]

In [43]:
weights=hotel_df["Humidity"]

coordinates=hotel_df[["Latitude", "Longtitude"]]

markers = gmaps.marker_layer(coordinates)

fig.add_layer(markers)
fig




fig = gmaps.figure()


heat_layer = gmaps.heatmap_layer(locations, weights= weights,
                                 dissipating=False, max_intensity=50,
                                 point_radius=3)



fig.add_layer(heat_layer)


fig

Figure(layout=FigureLayout(height='420px'))